### PR TITLE
Rubyl 81 change calc icons

### PR DESCRIPTION
**Pull request by DmitriyShevtsov**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

**Review by PrincTwilig — APPROVED** [review]

**Review by denysiuk — APPROVED** [review]
Everything's good, will also be great if you add screenshots of how it looked before and how if looks now in the description.

**Comment by opazyniuk** [comment]
please add a following updates:
- remove old icons
- add a screenshot with how it looks before/after these changes

**Review by opazyniuk — CHANGES_REQUESTED** [review]
leaved comment above

**Comment by DmitriyShevtsov** [comment]
> leaved comment above

> please add a following updates:
> 
> * remove old icons
> * add a screenshot with how it looks before/after these changes
=================================================================

- older icons removed

- please check the "before" and "after" state screenshots
icons_before
icons_after

**Review by opazyniuk — APPROVED** [review]

**Pull request merged**
